version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Update yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ~/.cache/yarn
      - run:
          name: Test
          command: yarn test
workflows:
  version: 2
  test:
    jobs:
      - test
